server:
  port: 8083

spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
         - Path=/user/**
         
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
         - Path=/hotel/**,/staff/**
         
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
         - Path=/rating/**
         
  config:
    import: optional:configserver:http://localhost:8084  
    
okta:
  oauth2:
    issuer: https://dev-04981279.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa8zlpojaRbdaLnF5d7
    client-secret: CDhjjkhRYQY8zvmOvhw0OkQ2cFh5ACffOa514FsF
    scopes: openid, profile, email, offline_access

      

